cache: pip
language: python
python: 2.7
sudo: false
install:
- pip install git+git://github.com/grow/grow
script:
- cd example
- grow install
- grow --auth-key-file=grow-ext-budou-ci.json build
before_install:
- openssl aes-256-cbc -K $encrypted_ae9dd2f00bd8_key -iv $encrypted_ae9dd2f00bd8_iv
  -in example/grow-ext-budou-ci.json.enc -out example/grow-ext-budou-ci.json -d
