cache: pip
language: python
python: 2.7
sudo: false
install:
- pip install git+git://github.com/grow/grow
script:
- cd testdata
- AUTH_KEY_FILE=grow-ext-budou-ci.json
- grow install
- grow build
before_install:
- openssl aes-256-cbc -K $encrypted_ae9dd2f00bd8_key -iv $encrypted_ae9dd2f00bd8_iv
  -in testdata/grow-ext-budou-ci.json.enc -out testdata/grow-ext-budou-ci.json -d
